### PR TITLE
Updated apt-get packages to latest MISP-modules version

### PR DESCRIPTION
**Pull request by gl4ssiest**

### CODE REVIEW

**Comment by angarod** [comment]
This merge request fix #41

**Comment by ventz** [comment]
@angarod Can you add a comment on the ports about tcp/6666? (see line above)

**Comment by angarod** [comment]
@ventz is right, this pull request adds a port (6666/TCP) to the image. However this is the port listened by default for many modules in misp-modules.

**Comment by ventz** [comment]
@angarod I know this is old (people had been `adding -p 6666:6666`) -- added the port and many other things. Pushing out soon.

**Pull request closed without merging**
